controllers/PostController.php
<?php

namespace app\controllers;

use Yii;
use app\models\TestForm;
use app\models\Category;


class PostController extends AppController {

	public $layout = 'basic';

//	public function beforeAction($action) {
//		// Отключение csrf валидации
//		if($action->id == 'index') {
//			$this->enableCsrfValidation = false;
//		}
//
//		return parent::beforeAction($action);
//	}

	public function actionIndex() {

		if(Yii::$app->request->isAjax) {

//			debug($_POST);

			debug(Yii::$app->request->post());

			return 'test';
		}


		/*
		 * Обновление записи в БД
		 */
//		$post = TestForm::findOne(3);
//		$post->email = '3@2.com';
//		$post->save();


		/*
		 * Удаление записи из БД
		 */
//		$post = TestForm::findOne(2);
//		$post->delete();
		// Удаление записей, в которых id > 3
		TestForm::deleteAll(['>', 'id', 3]);


		/*
		 * Запись записи в БД
		 */
		$model = new TestForm();

//		$model->name = 'Автор';
//		$model->email = 'mail@mail.com';
//		$model->text = 'Текст сообщения';
//		$model->save();

		// Если данные загружены
		if($model->load(Yii::$app->request->post())) {
//			debug(Yii::$app->request->post());
			if($model->save()) {
				Yii::$app->session->setFlash('success', 'Данные приняты');
				// Очистка формы после отправки
				return $this->refresh();
			}
			else {
				Yii::$app->session->setFlash('error', 'Ошибка');
			}
		}

		$this->view->title = 'Все статьи';

		return $this->render('test', compact('model'));
	}

	public function actionTest() {

		return $this->render('test');
	}

	public function actionShow() {

//		$this->layout = 'basic';

		$this->view->title = 'Одна статья';
		$this->view->registerMetaTag(['name' => 'keywords', 'content' => 'ключевые слова']);
		$this->view->registerMetaTag(['name' => 'description', 'content' => 'описание страницы']);

//		$cats = Category::find()->all();
//		$cats = Category::find()->orderBy(['id' => SORT_DESC])->all();
//		$cats = Category::find()->asArray()->where('parent=691')->all();
//		$cats = Category::find()->asArray()->where(['parent' => 691])->all();
		// %-маркеры фреймворк ставит самостоятельно
//		$cats = Category::find()->asArray()->where(['like', 'title', 'pp'])->all();
//		$cats = Category::find()->asArray()->where(['<=', 'id', 695])->all();
//		$cats = Category::find()->asArray()->where('parent=691')->limit(2)->all();
		// Избыточный запрос на выборку одной записи
//		$cats = Category::find()->asArray()->where('parent=691')->one();
		// Неизбыточный запрос на выборку одной записи
//		$cats = Category::find()->asArray()->where('parent=691')->limit(1)->one();
//		$cats = Category::find()->asArray()->where('parent=691')->count();
//		$cats = Category::findOne(['parent' => 691]);
//		$cats = Category::findAll(['parent' => 691]);

//		$query = "SELECT * FROM categories WHERE title LIKE '%pp%'";
		// Безопасный аналог запроса для избежания sql-иньекций
//		$query = "SELECT * FROM categories WHERE title LIKE :search";
//		$cats = Category::findBySql($query, [':search' => '%pp%'])->all();

//		$cats = Category::findOne(694);
//		$cats = Category::find()->with('products')->where('id=694')->all();
		// Отложенная загрузка
//		$cats = Category::find()->all();
		// Жадная загрузка
		$cats = Category::find()->with('products')->all();

		return $this->render('show', compact('cats'));
	}

}

views/layouts/basic.php
<?php
use app\assets\AppAsset;
use yii\helpers\Html;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>

<!doctype html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?php echo Html::csrfMetaTags() ?>
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?= Html::encode($this->title) ?></title>
	<?php $this->head() ?>
</head>
<body>
	<?php $this->beginBody() ?>

	<div class="wrap">
        <div class="container">

            <ul class="nav nav-pills">
                <li role="presentation" class="active"><?php echo Html::a('Главная', '/web/'); ?></li>
                <li role="presentation"><?php echo Html::a('Статьи', ['post/index']); ?></li>
                <li role="presentation"><?php echo Html::a('Статья', ['post/show']); ?></li>
            </ul>

            <?php if(isset($this->blocks['block1'])) : ?>
                <?php echo $this->blocks['block1']; ?>
            <?php endif; ?>

	        <?php echo $content; ?>

        </div>
    </div>



	<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use yii\helpers\Url;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">

	<?php
	NavBar::begin([
		'brandLabel' => Yii::$app->name,
		'brandUrl' => Yii::$app->homeUrl,
		'options' => [
			'class' => 'navbar-inverse navbar-fixed-top',
		],
	]);
	echo Nav::widget([
		'options' => ['class' => 'navbar-nav navbar-right'],
		'items' => [
			['label' => 'Home', 'url' => '/'],
			['label' => 'Articles', 'url' => ['/post/index']],
			['label' => 'About', 'url' => ['/about']],
			['label' => 'Contact', 'url' => ['/contact']],
			Yii::$app->user->isGuest ? (
			['label' => 'Login', 'url' => ['/login']]
			) : (
				'<li>'
				. Html::beginForm(['/site/logout'], 'post')
				. Html::submitButton(
					'Logout (' . Yii::$app->user->identity->username . ')',
					['class' => 'btn btn-link logout']
				)
				. Html::endForm()
				. '</li>'
			)
		],
	]);
	NavBar::end();
	?>

    <div class="container">
        <a href="<?php Url::to('/') ?>">Home</a>
        <?php echo Html::a('About', Url::to(['/about'])) ?>
        <?php echo Html::a('Contact', Url::to(['/contact'])) ?>

        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>